version: '3.3'
name: dev
services:
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file: dev.env

  backend:
    build: ./backend/
    restart: always
    env_file: dev.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: sh -c "python3 manage.py collectstatic --no-input &&
                    python3 manage.py makemigrations --no-input &&
                    python3 manage.py makemigrations --merge --no-input &&
                    python3 manage.py migrate &&
                    python3 manage.py createsuperuser --no-input || true &&
                    python3 manage.py db_script &&
                    python3 manage.py runserver 0.0.0.0:80"

  frontend:
    build:
      context: ./frontend
      target: base
    restart: always
    volumes:
      - ./frontend:/app
      - node_data:/app/node_modules
    command: yarn quasar dev

  proxy:
    image: nginx:stable-alpine3.17-slim
    restart: always
    volumes:
      - ./proxy/dev/dev.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  node_data:
  db_data:
