# Generated by Django 4.2 on 2023-07-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип дна',
                'verbose_name_plural': 'Типы дна',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CharacteristicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объекта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=200, verbose_name='Название заказа')),
                ('service_group',
                 models.CharField(choices=[('underwater',
                                            'Осмотр подводной части объекта'),
                                           ('surface',
                                            'Осмотр надводной части объекта'),
                                           ('3d-model',
                                            'Создание 3D-модели объекта'),
                                           ('report',
                                            'Составление отчета об осмотре'),
                                           ('defects',
                                            'Автоматический поиск дефектов'),
                                           ('deffects-report',
                                            'Создание отчета о дефектах')],
                                  max_length=200,
                                  verbose_name='Тип услуги')),
                ('map_latitude', models.CharField(
                    max_length=200, verbose_name='Широта')),
                ('map_longitude', models.CharField(
                    max_length=200, verbose_name='Долгота')),
                ('research_surface', models.IntegerField(
                    verbose_name='Площадь обследования')),
                ('water_turbidity', models.IntegerField(verbose_name='Видимость')),
                ('flow', models.IntegerField(verbose_name='Скорость течения воды')),
                ('price', models.IntegerField(verbose_name='Стоимость услуги')),
                ('deadline', models.DateTimeField(
                    verbose_name='Крайний срок выполнения')),
                ('created', models.DateTimeField(
                    auto_now=True, verbose_name='Дата создания заказа')),
                ('additional_description', models.TextField(
                    verbose_name='Дополнительное описание')),
                ('status',
                 models.CharField(choices=[('created',
                                            'Создан'),
                                           ('in_process',
                                            'В процессе'),
                                           ('completed',
                                            'Выполнен'),
                                           ('canceled',
                                            'Отменён')],
                                  max_length=200,
                                  verbose_name='Статус заказа')),
                ('model', models.CharField(blank=True,
                 max_length=200, verbose_name='Ссылка на 3D модель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='ordercharacteristic',
                                   to='orders.characteristicgroup',
                                   verbose_name='Тип объекта')),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='ordercharacteristic',
                                   to='orders.order',
                                   verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Характеристика объекта',
                'verbose_name_plural': 'Характеристики объекта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderBottom',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='orderbottom',
                                   to='orders.bottomgroup',
                                   verbose_name='Тип дна')),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='orderbottom',
                                   to='orders.order',
                                   verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Тип дна в заказе',
                'verbose_name_plural': 'Типы дна в заказе',
                'ordering': ['id'],
            },
        ),
    ]
