# Generated by Django 4.2 on 2023-07-20 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='order',
            name='bottom_group',
            field=models.ManyToManyField(
                related_name='orders',
                through='orders.OrderBottom',
                to='orders.bottomgroup',
                verbose_name='Тип дна'),
        ),
        migrations.AddField(
            model_name='order',
            name='characteristic_group',
            field=models.ManyToManyField(
                related_name='orders',
                through='orders.OrderCharacteristic',
                to='orders.characteristicgroup',
                verbose_name='Характеристика объекта'),
        ),
        migrations.AddConstraint(
            model_name='ordercharacteristic',
            constraint=models.UniqueConstraint(
                fields=(
                    'order',
                    'characteristic'),
                name='unique_characteristic_in_order'),
        ),
        migrations.AddConstraint(
            model_name='orderbottom',
            constraint=models.UniqueConstraint(
                fields=('order', 'bottom'), name='unique_bottom_in_order'),
        ),
    ]
