# Generated by Django 4.2 on 2023-07-23 10:14

from django.db import migrations, models

import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.FileField(
                default='models/empty_order.ply',
                upload_to=orders.models.author_directory_path,
                verbose_name='Файл 3D модели'),
        ),
    ]
